[programs.localnet]
gem_bank = "57rL5hf9Gj5aHKyW4563wMKi6eLuSuDQdqvoYbuS3bbV"
gem_farm = "ZfRV6mhNAyWnW22XvhpidZQHYhpTXbsQD36j25SXPmF"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "localnet"
wallet = "/Users/reece/.config/solana/gemfarm.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"